[[constraint]]
    branch = "master"
    name = "github.com/gorilla/mux"

[[constraint]]
    branch = "master"
    name = "github.com/stretchr/testify"

[[constraint]]
    branch = "v2"
    name = "gopkg.in/mgo.v2"

[[constraint]]
    branch = "master"
    name = "github.com/sirupsen/logrus"

[[constraint]]
    branch = "master"
    name = "golang.org/x/crypto"

[[constraint]]
    branch = "master"
    name = "github.com/dgrijalva/jwt-go"
